import logging

from prometheus_client import Counter, Gauge, Histogram, start_http_server

logger = logging.getLogger(__name__)

connector_requests_total = Counter(
    "connector_requests_total",
    "Total connector requests by source and status",
    ["source", "status"],
)

cdc_events_total = Counter(
    "cdc_events_total",
    "Total CDC events generated by event type",
    ["event_type"],
)

pipeline_duration_seconds = Histogram(
    "pipeline_duration_seconds",
    "Pipeline execution duration in seconds",
    ["route_id"],
    buckets=[1, 5, 10, 30, 60, 120, 300, 600],
)

connector_flights_found = Gauge(
    "connector_flights_found",
    "Number of flights found in the last connector run",
    ["source"],
)

_server_started = False


def start_metrics_server(port: int = 8000) -> None:
    global _server_started
    if _server_started:
        return
    try:
        start_http_server(port)
        _server_started = True
        logger.info("Prometheus metrics server started on port %d", port)
    except OSError:
        # Port already in use — another worker process started it
        _server_started = True
        logger.warning("Prometheus metrics server port %d already in use, skipping", port)
